"""
PyTorch Fundamentals

Tensors, autograd, nn.Module, training loops, and the PyTorch idioms used in every later lesson.

TODO: implement teaching example for this topic.
This is a placeholder generated by scripts/scaffold.py.
"""


def main():
    raise NotImplementedError("Example for 'PyTorch Fundamentals' has not been written yet.")


if __name__ == "__main__":
    main()
