"""
LoRA and QLoRA

Low-rank adapters and 4-bit quantized base weights for fine-tuning on consumer hardware.

TODO: implement teaching example for this topic.
This is a placeholder generated by scripts/scaffold.py.
"""


def main():
    raise NotImplementedError("Example for 'LoRA and QLoRA' has not been written yet.")


if __name__ == "__main__":
    main()
