"""
Building an End-to-End Chatbot

Combine a base/instruction-tuned model with a simple serving layer into a working chatbot.

TODO: implement teaching example for this topic.
This is a placeholder generated by scripts/scaffold.py.
"""


def main():
    raise NotImplementedError("Example for 'Building an End-to-End Chatbot' has not been written yet.")


if __name__ == "__main__":
    main()
