"""
Multi-Agent Systems

Coordinating multiple specialized LLM agents to solve tasks a single agent struggles with.

TODO: implement teaching example for this topic.
This is a placeholder generated by scripts/scaffold.py.
"""


def main():
    raise NotImplementedError("Example for 'Multi-Agent Systems' has not been written yet.")


if __name__ == "__main__":
    main()
