"""
Automatic Prompt Optimization

Programmatically searching/refining prompts instead of hand-tuning them.

TODO: implement teaching example for this topic.
This is a placeholder generated by scripts/scaffold.py.
"""


def main():
    raise NotImplementedError("Example for 'Automatic Prompt Optimization' has not been written yet.")


if __name__ == "__main__":
    main()
