"""
Building a RAG Q&A System

A complete retrieval-augmented Q&A app over a real document set.

TODO: implement teaching example for this topic.
This is a placeholder generated by scripts/scaffold.py.
"""


def main():
    raise NotImplementedError("Example for 'Building a RAG Q&A System' has not been written yet.")


if __name__ == "__main__":
    main()
