"""
Instruction Tuning (SFT)

Supervised fine-tuning on instruction/response pairs to turn a base model into an assistant.

TODO: implement teaching example for this topic.
This is a placeholder generated by scripts/scaffold.py.
"""


def main():
    raise NotImplementedError("Example for 'Instruction Tuning (SFT)' has not been written yet.")


if __name__ == "__main__":
    main()
