"""
Pretraining Objectives

Causal language modeling, masked language modeling, and span corruption objectives compared.

TODO: implement teaching example for this topic.
This is a placeholder generated by scripts/scaffold.py.
"""


def main():
    raise NotImplementedError("Example for 'Pretraining Objectives' has not been written yet.")


if __name__ == "__main__":
    main()
