"""
Quantization

INT8/INT4 quantization, GPTQ, and AWQ for shrinking model size and speeding up inference.

TODO: implement teaching example for this topic.
This is a placeholder generated by scripts/scaffold.py.
"""


def main():
    raise NotImplementedError("Example for 'Quantization' has not been written yet.")


if __name__ == "__main__":
    main()
