"""
The Alignment Problem

Why raw next-token prediction isn't enough, and what 'aligned' means in practice.

TODO: implement teaching example for this topic.
This is a placeholder generated by scripts/scaffold.py.
"""


def main():
    raise NotImplementedError("Example for 'The Alignment Problem' has not been written yet.")


if __name__ == "__main__":
    main()
