"""
RNNs, LSTMs and GRUs

Sequential modeling with recurrence, vanishing/exploding gradients, and gating mechanisms that fixed them.

TODO: implement teaching example for this topic.
This is a placeholder generated by scripts/scaffold.py.
"""


def main():
    raise NotImplementedError("Example for 'RNNs, LSTMs and GRUs' has not been written yet.")


if __name__ == "__main__":
    main()
