"""
Domain-Specific Fine-tuning Case Study

End-to-end case study: fine-tuning a model for a narrow, real-world domain/task.

TODO: implement teaching example for this topic.
This is a placeholder generated by scripts/scaffold.py.
"""


def main():
    raise NotImplementedError("Example for 'Domain-Specific Fine-tuning Case Study' has not been written yet.")


if __name__ == "__main__":
    main()
