"""
Encoder-Decoder Models: T5 and BART

Text-to-text framing, span corruption, and when encoder-decoder beats decoder-only.

TODO: implement teaching example for this topic.
This is a placeholder generated by scripts/scaffold.py.
"""


def main():
    raise NotImplementedError("Example for 'Encoder-Decoder Models: T5 and BART' has not been written yet.")


if __name__ == "__main__":
    main()
