"""
Encoder-Decoder Models: T5 and BART

Three parts:
  1. T5-style span corruption -- replace contiguous spans with sentinel
     tokens, target is only the missing pieces.
  2. BART-style denoising -- four corruption strategies (token masking,
     token deletion, sentence permutation, document rotation), target
     is always the full original text.
  3. The actual encoder-decoder architecture from the README's diagram --
     a bidirectional encoder stack and a causal decoder stack connected
     by cross-attention -- built from scratch and TRAINED end to end on
     real T5-style span-corruption pairs generated by Part 1, then used
     to generate (fill in the missing spans of a held-out sentence).

Runtime: ~1-2 minutes on a CPU (Part 3 trains for 1200 steps).

Run:
    python example.py
"""

import math
import random

import torch
import torch.nn as nn
import torch.nn.functional as F

random.seed(0)
torch.manual_seed(0)


# ---------------------------------------------------------------------------
# 1. T5-style span corruption
# ---------------------------------------------------------------------------

def t5_span_corruption(tokens, noise_density=0.15, max_span_length=3):
    n = len(tokens)
    target_noise = max(1, round(n * noise_density))
    corrupted = [False] * n
    noise_so_far = 0

    attempts = 0
    while noise_so_far < target_noise and attempts < 100:
        attempts += 1
        start = random.randrange(n)
        span_len = random.randint(1, max_span_length)
        span_len = min(span_len, n - start, target_noise - noise_so_far)
        if span_len <= 0 or any(corrupted[start:start + span_len]):
            continue   # overlaps an already-chosen span, or doesn't fit -- try again
        for j in range(start, start + span_len):
            corrupted[j] = True
        noise_so_far += span_len

    input_tokens, target_tokens = [], []
    sentinel_id = 0
    i = 0
    while i < n:
        if corrupted[i]:
            sentinel = f"<extra_id_{sentinel_id}>"
            input_tokens.append(sentinel)
            target_tokens.append(sentinel)
            while i < n and corrupted[i]:
                target_tokens.append(tokens[i])
                i += 1
            sentinel_id += 1
        else:
            input_tokens.append(tokens[i])
            i += 1
    target_tokens.append(f"<extra_id_{sentinel_id}>")  # T5 terminates with one final sentinel
    return input_tokens, target_tokens


def t5_demo():
    print("=" * 70)
    print("1. T5-STYLE SPAN CORRUPTION")
    print("=" * 70)
    sentences = [
        "the quick brown fox jumps over the lazy dog",
        "the sun rises over the dark forest every morning",
    ]
    for sentence in sentences:
        tokens = sentence.split()
        corrupted_input, target = t5_span_corruption(tokens)
        print(f"  original: {' '.join(tokens)}")
        print(f"  input:    {' '.join(corrupted_input)}")
        print(f"  target:   {' '.join(target)}\n")
    print("-> The target is much SHORTER than the input -- it only reconstructs")
    print("   the missing spans, tagged by sentinel, not the whole sentence.")


# ---------------------------------------------------------------------------
# 2. BART-style denoising corruptions
# ---------------------------------------------------------------------------

def bart_token_masking(tokens, mask_prob=0.3):
    corrupted = [("[MASK]" if random.random() < mask_prob else t) for t in tokens]
    return corrupted, list(tokens)   # target = the FULL original sequence


def bart_token_deletion(tokens, delete_prob=0.3):
    corrupted = [t for t in tokens if random.random() >= delete_prob]
    return corrupted, list(tokens)


def bart_sentence_permutation(sentences):
    shuffled = sentences[:]
    # Reshuffle until it's actually different -- for a document with only a
    # handful of sentences, random.shuffle CAN legitimately land back on the
    # original order; we retry purely so this demo always shows a real change.
    for _ in range(20):
        random.shuffle(shuffled)
        if shuffled != sentences or len(sentences) < 2:
            break
    return shuffled, sentences   # target = the correct original order


def bart_document_rotation(tokens):
    if len(tokens) < 2:
        return list(tokens), list(tokens)
    pivot = random.randint(1, len(tokens) - 1)
    rotated = tokens[pivot:] + tokens[:pivot]
    return rotated, list(tokens)   # target = the true original order/start


def bart_demo():
    print("\n" + "=" * 70)
    print("2. BART-STYLE DENOISING (target is always the FULL original text)")
    print("=" * 70)

    tokens = "the quick brown fox jumps over the lazy dog".split()

    corrupted, target = bart_token_masking(tokens)
    print("Token masking:")
    print(f"  input:  {' '.join(corrupted)}")
    print(f"  target: {' '.join(target)}\n")

    corrupted, target = bart_token_deletion(tokens)
    print("Token deletion (model must infer WHERE tokens are missing, not just what):")
    print(f"  input:  {' '.join(corrupted)}")
    print(f"  target: {' '.join(target)}\n")

    sentences = [
        "the fox saw the hen.",
        "the hen ran into the barn.",
        "the fox followed close behind.",
    ]
    shuffled, original_order = bart_sentence_permutation(sentences)
    print("Sentence permutation:")
    print(f"  input:  {' '.join(shuffled)}")
    print(f"  target: {' '.join(original_order)}\n")

    corrupted, target = bart_document_rotation(tokens)
    print("Document rotation (model must identify the TRUE starting point):")
    print(f"  input:  {' '.join(corrupted)}")
    print(f"  target: {' '.join(target)}")

    print("\n-> Every BART target is the complete, correctly-ordered original text --")
    print("   a strictly harder reconstruction target than T5's 'just the missing")
    print("   pieces', which is exactly why BART tends to shine on generation-heavy")
    print("   tasks like summarization: it was always trained to produce full,")
    print("   fluent text, never just isolated spans.")


# ---------------------------------------------------------------------------
# 3. The actual encoder-decoder architecture from the README's diagram,
# built from scratch and trained end to end on real T5-style span-corruption
# pairs (using t5_span_corruption from Part 1 above as the data pipeline).
# ---------------------------------------------------------------------------

CORPUS_SENTENCES = [
    "the quick brown fox jumps over the lazy dog",
    "the sun rises over the dark forest every morning",
    "the moon shines over the dark forest every night",
    "birds sing songs in the tall green trees",
    "the small dog barks at the tall cat",
    "the tall cat runs away from the small dog",
    "the lazy dog barks at the quick brown fox",
    "the quick brown fox runs into the dark forest",
]
MAX_SPAN_LENGTH = 2
NUM_SENTINELS = 4   # enough for MAX_SPAN_LENGTH=2 corruption on these short sentences

SPECIALS = ["[PAD]", "[BOS]", "[EOS]"]
SENTINELS = [f"<extra_id_{i}>" for i in range(NUM_SENTINELS)]
WORDS = sorted({w for s in CORPUS_SENTENCES for w in s.split()})
VOCAB = SPECIALS + SENTINELS + WORDS
STOI = {w: i for i, w in enumerate(VOCAB)}
ITOS = {i: w for i, w in enumerate(VOCAB)}
VOCAB_SIZE = len(VOCAB)
PAD_ID, BOS_ID, EOS_ID = (STOI[t] for t in SPECIALS)

MAX_SRC_LEN = 12
MAX_TGT_LEN = 10


def encode_padded(word_tokens, max_len, append_eos=False):
    ids = [STOI[w] for w in word_tokens]
    if append_eos:
        ids = ids + [EOS_ID]
    ids = ids[:max_len]
    ids = ids + [PAD_ID] * (max_len - len(ids))
    return ids


def make_training_pair():
    """One (encoder_input, decoder_input, decoder_target) triple, built by
    running Part 1's real T5 span-corruption function on a random sentence."""
    tokens = random.choice(CORPUS_SENTENCES).split()
    input_tokens, target_tokens = t5_span_corruption(
        tokens, noise_density=0.3, max_span_length=MAX_SPAN_LENGTH
    )
    encoder_input = encode_padded(input_tokens, MAX_SRC_LEN)
    # Standard teacher-forcing setup: decoder INPUT is the target shifted
    # right (prefixed with [BOS]); decoder TARGET is the target itself,
    # ending in [EOS] so the model also learns when to stop generating.
    decoder_input = encode_padded([("[BOS]")] + target_tokens, MAX_TGT_LEN)
    decoder_target = encode_padded(target_tokens, MAX_TGT_LEN, append_eos=True)
    return encoder_input, decoder_input, decoder_target


def get_training_batch(batch_size):
    triples = [make_training_pair() for _ in range(batch_size)]
    enc_in, dec_in, dec_tgt = zip(*triples)
    return (
        torch.tensor(enc_in, dtype=torch.long),
        torch.tensor(dec_in, dtype=torch.long),
        torch.tensor(dec_tgt, dtype=torch.long),
    )


class MultiHeadAttention(nn.Module):
    """Same mechanism used throughout this course -- generalized so the
    query sequence can differ from the key/value sequence. That's what lets
    ONE class serve as encoder self-attention, decoder self-attention, AND
    the decoder's cross-attention (the box in the README diagram where
    Q comes from the decoder but K/V come from the encoder's output)."""

    def __init__(self, d_model, num_heads):
        super().__init__()
        assert d_model % num_heads == 0
        self.num_heads = num_heads
        self.d_k = d_model // num_heads
        self.W_q = nn.Linear(d_model, d_model)
        self.W_k = nn.Linear(d_model, d_model)
        self.W_v = nn.Linear(d_model, d_model)
        self.W_o = nn.Linear(d_model, d_model)

    def _split_heads(self, x):
        batch, T, d_model = x.shape
        return x.view(batch, T, self.num_heads, self.d_k).transpose(1, 2)

    def forward(self, query_input, key_value_input, mask=None):
        batch, T_q, d_model = query_input.shape
        Q = self._split_heads(self.W_q(query_input))
        K = self._split_heads(self.W_k(key_value_input))
        V = self._split_heads(self.W_v(key_value_input))

        scores = (Q @ K.transpose(-2, -1)) / math.sqrt(self.d_k)
        if mask is not None:
            scores = scores.masked_fill(~mask, float("-inf"))
        weights = F.softmax(scores, dim=-1)
        out = (weights @ V).transpose(1, 2).contiguous().view(batch, T_q, d_model)
        return self.W_o(out)


class FeedForward(nn.Module):
    def __init__(self, d_model, d_ff):
        super().__init__()
        self.fc1 = nn.Linear(d_model, d_ff)
        self.fc2 = nn.Linear(d_ff, d_model)

    def forward(self, x):
        return self.fc2(F.gelu(self.fc1(x)))


class EncoderBlock(nn.Module):
    def __init__(self, d_model, num_heads, d_ff):
        super().__init__()
        self.ln1 = nn.LayerNorm(d_model)
        self.self_attn = MultiHeadAttention(d_model, num_heads)
        self.ln2 = nn.LayerNorm(d_model)
        self.ffn = FeedForward(d_model, d_ff)

    def forward(self, x, src_pad_mask):
        normed = self.ln1(x)
        x = x + self.self_attn(normed, normed, mask=src_pad_mask)  # bidirectional self-attention
        x = x + self.ffn(self.ln2(x))
        return x


class DecoderBlock(nn.Module):
    def __init__(self, d_model, num_heads, d_ff):
        super().__init__()
        self.ln1 = nn.LayerNorm(d_model)
        self.self_attn = MultiHeadAttention(d_model, num_heads)
        self.ln2 = nn.LayerNorm(d_model)
        self.cross_attn = MultiHeadAttention(d_model, num_heads)
        self.ln3 = nn.LayerNorm(d_model)
        self.ffn = FeedForward(d_model, d_ff)

    def forward(self, x, encoder_output, self_mask, cross_mask):
        normed = self.ln1(x)
        x = x + self.self_attn(normed, normed, mask=self_mask)          # causal self-attention
        # Cross-attention: query from the DECODER, key/value from the ENCODER --
        # the one box in the README diagram with no equivalent in Lessons 1-2.
        x = x + self.cross_attn(self.ln2(x), encoder_output, mask=cross_mask)
        x = x + self.ffn(self.ln3(x))
        return x


class EncoderDecoderModel(nn.Module):
    """The full architecture from the README diagram: an encoder stack (
    bidirectional self-attention) and a decoder stack (causal self-attention
    + cross-attention into the encoder's output), sharing one vocabulary --
    exactly T5's setup, where source and target are drawn from the same
    text-to-text vocabulary."""

    def __init__(self, vocab_size, d_model, num_heads, d_ff, num_layers, max_len):
        super().__init__()
        self.token_embedding = nn.Embedding(vocab_size, d_model)
        self.position_embedding = nn.Embedding(max_len, d_model)
        self.encoder_blocks = nn.ModuleList(
            [EncoderBlock(d_model, num_heads, d_ff) for _ in range(num_layers)]
        )
        self.decoder_blocks = nn.ModuleList(
            [DecoderBlock(d_model, num_heads, d_ff) for _ in range(num_layers)]
        )
        self.final_norm = nn.LayerNorm(d_model)
        self.output_head = nn.Linear(d_model, vocab_size)

    def embed(self, token_ids):
        T = token_ids.shape[1]
        positions = torch.arange(T, device=token_ids.device)
        return self.token_embedding(token_ids) + self.position_embedding(positions)

    def encode(self, src_ids):
        src_pad_mask = (src_ids != PAD_ID).view(src_ids.shape[0], 1, 1, -1)  # (batch,1,1,src_len)
        x = self.embed(src_ids)
        for block in self.encoder_blocks:
            x = block(x, src_pad_mask)
        return x, src_pad_mask

    def decode(self, tgt_ids, encoder_output, src_pad_mask):
        batch, T = tgt_ids.shape
        tgt_pad_mask = (tgt_ids != PAD_ID).view(batch, 1, 1, T)          # (batch,1,1,T)
        causal = torch.tril(torch.ones(T, T, dtype=torch.bool, device=tgt_ids.device))
        self_mask = causal.view(1, 1, T, T) & tgt_pad_mask               # causal AND not-padding
        x = self.embed(tgt_ids)
        for block in self.decoder_blocks:
            x = block(x, encoder_output, self_mask, src_pad_mask)
        x = self.final_norm(x)
        return self.output_head(x)   # (batch, T, vocab_size)

    def forward(self, src_ids, tgt_ids):
        encoder_output, src_pad_mask = self.encode(src_ids)
        return self.decode(tgt_ids, encoder_output, src_pad_mask)

    @torch.no_grad()
    def generate(self, src_ids, max_new_tokens):
        encoder_output, src_pad_mask = self.encode(src_ids)
        generated = torch.full((src_ids.shape[0], 1), BOS_ID, dtype=torch.long)
        for _ in range(max_new_tokens):
            logits = self.decode(generated, encoder_output, src_pad_mask)
            next_token = logits[:, -1, :].argmax(dim=-1, keepdim=True)
            generated = torch.cat([generated, next_token], dim=1)
            if (next_token == EOS_ID).all():
                break
        return generated


def architecture_demo():
    print("\n" + "=" * 70)
    print("3. THE ACTUAL ENCODER-DECODER ARCHITECTURE, BUILT AND TRAINED")
    print("=" * 70)
    print(f"Shared vocabulary ({VOCAB_SIZE} tokens): specials + {NUM_SENTINELS} sentinels "
          f"+ {len(WORDS)} words")

    model = EncoderDecoderModel(
        VOCAB_SIZE, d_model=64, num_heads=4, d_ff=256, num_layers=2,
        max_len=max(MAX_SRC_LEN, MAX_TGT_LEN),
    )
    print(f"Model parameter count: {sum(p.numel() for p in model.parameters()):,}")

    optimizer = torch.optim.AdamW(model.parameters(), lr=3e-3)
    print("\nTraining on real T5 span-corruption pairs (loss ignores [PAD] positions)...")
    for step in range(1, 1201):
        enc_in, dec_in, dec_tgt = get_training_batch(batch_size=32)
        logits = model(enc_in, dec_in)
        loss = F.cross_entropy(
            logits.view(-1, VOCAB_SIZE), dec_tgt.view(-1), ignore_index=PAD_ID
        )
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        if step % 300 == 0 or step == 1:
            print(f"  step {step:5d}  loss = {loss.item():.4f}")

    print("\nFilling in missing spans on held-out sentences (greedy decoding):")
    model.eval()
    for sentence in CORPUS_SENTENCES[:3]:
        tokens = sentence.split()
        input_tokens, true_target = t5_span_corruption(
            tokens, noise_density=0.3, max_span_length=MAX_SPAN_LENGTH
        )
        src_ids = torch.tensor([encode_padded(input_tokens, MAX_SRC_LEN)])
        generated = model.generate(src_ids, max_new_tokens=MAX_TGT_LEN)[0].tolist()
        predicted = [ITOS[i] for i in generated[1:] if i not in (PAD_ID, EOS_ID)]

        print(f"  input:     {' '.join(input_tokens)}")
        print(f"  true:      {' '.join(true_target)}")
        print(f"  predicted: {' '.join(predicted)}\n")

    print("-> The encoder saw the corrupted sentence with NO causal mask (bidirectional --")
    print("   same as Lesson 2's BERT); the decoder generated the missing spans one")
    print("   sentinel-tagged token at a time, using CAUSAL self-attention over what")
    print("   it has produced so far PLUS cross-attention back into the encoder's full,")
    print("   bidirectionally-processed output. That combination -- bidirectional input")
    print("   understanding + autoregressive output generation -- is exactly what")
    print("   neither Lesson 1 (decoder-only) nor Lesson 2 (encoder-only) can do alone.")


def main():
    t5_demo()
    bart_demo()
    architecture_demo()


if __name__ == "__main__":
    main()
