"""
Positional Encoding

Absolute sinusoidal encodings, learned positions, and an intro to RoPE/ALiBi (deep dives later).

TODO: implement teaching example for this topic.
This is a placeholder generated by scripts/scaffold.py.
"""


def main():
    raise NotImplementedError("Example for 'Positional Encoding' has not been written yet.")


if __name__ == "__main__":
    main()
