"""
Prompting Basics: Zero-Shot and Few-Shot

How in-context learning works and how to design effective zero/few-shot prompts.

TODO: implement teaching example for this topic.
This is a placeholder generated by scripts/scaffold.py.
"""


def main():
    raise NotImplementedError("Example for 'Prompting Basics: Zero-Shot and Few-Shot' has not been written yet.")


if __name__ == "__main__":
    main()
