"""
Capstone Project Guidelines

Project ideas, rubric, and guidance for viewers to design their own capstone.

TODO: implement teaching example for this topic.
This is a placeholder generated by scripts/scaffold.py.
"""


def main():
    raise NotImplementedError("Example for 'Capstone Project Guidelines' has not been written yet.")


if __name__ == "__main__":
    main()
