"""
Direct Preference Optimization (DPO)

A simpler alternative to PPO that optimizes directly on preference pairs, no reward model needed.

TODO: implement teaching example for this topic.
This is a placeholder generated by scripts/scaffold.py.
"""


def main():
    raise NotImplementedError("Example for 'Direct Preference Optimization (DPO)' has not been written yet.")


if __name__ == "__main__":
    main()
