"""
Transformer Encoder-Decoder Architecture

How the original encoder-decoder stack fits together end to end, block by block.

TODO: implement teaching example for this topic.
This is a placeholder generated by scripts/scaffold.py.
"""


def main():
    raise NotImplementedError("Example for 'Transformer Encoder-Decoder Architecture' has not been written yet.")


if __name__ == "__main__":
    main()
