"""
Self-Attention and Multi-Head Attention

Queries/keys/values, scaled dot-product attention, and why multiple heads help.

TODO: implement teaching example for this topic.
This is a placeholder generated by scripts/scaffold.py.
"""


def main():
    raise NotImplementedError("Example for 'Self-Attention and Multi-Head Attention' has not been written yet.")


if __name__ == "__main__":
    main()
