"""
Prompt Tuning, Prefix Tuning and Adapters

Other parameter-efficient methods: soft prompts, prefix vectors, and bottleneck adapter layers.

TODO: implement teaching example for this topic.
This is a placeholder generated by scripts/scaffold.py.
"""


def main():
    raise NotImplementedError("Example for 'Prompt Tuning, Prefix Tuning and Adapters' has not been written yet.")


if __name__ == "__main__":
    main()
