"""
Building a Mini-Transformer / Mini-GPT From Scratch

Assemble every previous piece into a small, working decoder-only model trained on toy data.

TODO: implement teaching example for this topic.
This is a placeholder generated by scripts/scaffold.py.
"""


def main():
    raise NotImplementedError("Example for 'Building a Mini-Transformer / Mini-GPT From Scratch' has not been written yet.")


if __name__ == "__main__":
    main()
