"""
Encoder-Only Models: the BERT Family

Bidirectional context, masked language modeling, and BERT/RoBERTa-style pretraining.

TODO: implement teaching example for this topic.
This is a placeholder generated by scripts/scaffold.py.
"""


def main():
    raise NotImplementedError("Example for 'Encoder-Only Models: the BERT Family' has not been written yet.")


if __name__ == "__main__":
    main()
