"""
Introduction to NLP

Text representation (bag-of-words, TF-IDF), classic word embeddings, and why raw text needs to become numbers.

TODO: implement teaching example for this topic.
This is a placeholder generated by scripts/scaffold.py.
"""


def main():
    raise NotImplementedError("Example for 'Introduction to NLP' has not been written yet.")


if __name__ == "__main__":
    main()
