"""
Distributed Training Basics

Data parallelism, model/tensor parallelism, and ZeRO/FSDP-style memory sharding.

TODO: implement teaching example for this topic.
This is a placeholder generated by scripts/scaffold.py.
"""


def main():
    raise NotImplementedError("Example for 'Distributed Training Basics' has not been written yet.")


if __name__ == "__main__":
    main()
