"""
Decoder-Only Models: the GPT Family

Causal masking, autoregressive generation, and how GPT-1/2/3-style models are structured.

TODO: implement teaching example for this topic.
This is a placeholder generated by scripts/scaffold.py.
"""


def main():
    raise NotImplementedError("Example for 'Decoder-Only Models: the GPT Family' has not been written yet.")


if __name__ == "__main__":
    main()
