"""
Serving Frameworks

vLLM, TGI, and llama.cpp — how modern inference servers achieve high throughput.

TODO: implement teaching example for this topic.
This is a placeholder generated by scripts/scaffold.py.
"""


def main():
    raise NotImplementedError("Example for 'Serving Frameworks' has not been written yet.")


if __name__ == "__main__":
    main()
