"""
Mixture of Experts

Sparse expert routing, gating networks, and why MoE scales parameters without scaling compute linearly.

TODO: implement teaching example for this topic.
This is a placeholder generated by scripts/scaffold.py.
"""


def main():
    raise NotImplementedError("Example for 'Mixture of Experts' has not been written yet.")


if __name__ == "__main__":
    main()
