"""
Full Fine-tuning vs Parameter-Efficient Fine-tuning

Trade-offs of updating all weights vs a small adapter subset — cost, quality, and when each wins.

TODO: implement teaching example for this topic.
This is a placeholder generated by scripts/scaffold.py.
"""


def main():
    raise NotImplementedError("Example for 'Full Fine-tuning vs Parameter-Efficient Fine-tuning' has not been written yet.")


if __name__ == "__main__":
    main()
