"""
Tokenization

BPE, WordPiece, SentencePiece, and tiktoken — how raw text becomes model-ready token IDs.

TODO: implement teaching example for this topic.
This is a placeholder generated by scripts/scaffold.py.
"""


def main():
    raise NotImplementedError("Example for 'Tokenization' has not been written yet.")


if __name__ == "__main__":
    main()
