"""
Structured Output and Function Calling

Getting reliable JSON/schema-constrained output and invoking external functions/tools.

TODO: implement teaching example for this topic.
This is a placeholder generated by scripts/scaffold.py.
"""


def main():
    raise NotImplementedError("Example for 'Structured Output and Function Calling' has not been written yet.")


if __name__ == "__main__":
    main()
