"""
What is a Language Model

N-gram models, probability of a sequence, perplexity as a first evaluation metric.

TODO: implement teaching example for this topic.
This is a placeholder generated by scripts/scaffold.py.
"""


def main():
    raise NotImplementedError("Example for 'What is a Language Model' has not been written yet.")


if __name__ == "__main__":
    main()
