"""
Advanced RAG

Hybrid search, re-ranking, query rewriting/expansion, and other retrieval-quality upgrades.

TODO: implement teaching example for this topic.
This is a placeholder generated by scripts/scaffold.py.
"""


def main():
    raise NotImplementedError("Example for 'Advanced RAG' has not been written yet.")


if __name__ == "__main__":
    main()
