"""
Multimodal LLMs

Vision-language models, CLIP-style contrastive pretraining, and architectures like LLaVA.

TODO: implement teaching example for this topic.
This is a placeholder generated by scripts/scaffold.py.
"""


def main():
    raise NotImplementedError("Example for 'Multimodal LLMs' has not been written yet.")


if __name__ == "__main__":
    main()
