"""
KV Cache and Speculative Decoding

Why KV caching makes autoregressive generation fast, and how speculative decoding speeds it up further.

TODO: implement teaching example for this topic.
This is a placeholder generated by scripts/scaffold.py.
"""


def main():
    raise NotImplementedError("Example for 'KV Cache and Speculative Decoding' has not been written yet.")


if __name__ == "__main__":
    main()
