"""
Introduction to Transformers

Why 'Attention Is All You Need' replaced recurrence entirely — the big picture before the deep dive.

TODO: implement teaching example for this topic.
This is a placeholder generated by scripts/scaffold.py.
"""


def main():
    raise NotImplementedError("Example for 'Introduction to Transformers' has not been written yet.")


if __name__ == "__main__":
    main()
